#!/usr/bin/env node
/* Sign the curated catalog snapshot and write src/data/catalog-signature.js.
 * A fresh Ed25519 keypair is generated and the private key is discarded; only
 * the public key and signature are committed. Production signing keys stay
 * offline — this is a preview catalog key. Re-run after changing the catalog:
 *   make sign-catalog
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATALOG, CATALOG_META } from '../src/data/store-catalog.js';
import { signCatalog, catalogDigest } from '../src/core/catalog-sign.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const pair = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
const publicKey = Buffer.from(await crypto.subtle.exportKey('raw', pair.publicKey)).toString('base64');
const signature = await signCatalog(CATALOG, CATALOG_META, pair.privateKey);
const digest = await catalogDigest(CATALOG, CATALOG_META);

const out = `// Generated by scripts/sign-catalog.mjs — do not edit by hand.
// Preview catalog signing key; the private key was discarded after signing.
export const CATALOG_SIGNER = Object.freeze({
  publicKey: '${publicKey}',
  signature: '${signature}',
  digest: '${digest}',
});
`;
writeFileSync(join(root, 'src', 'data', 'catalog-signature.js'), out);
console.log('signed catalog snapshot ' + CATALOG_META.snapshot);
console.log('  listings  ' + CATALOG.length);
console.log('  digest    ' + digest);
console.log('  wrote     src/data/catalog-signature.js');
